### ISSUE TITLE
Dictionary on municipality name and avoid name mangling

### ISSUE THREAD

**Issue by bebosudo** [fabiocaccamo/python-codicefiscale#2]
Hi Fabio! First of all, thanks for this library.

I'm using it to validate some user input in a project, and I'd like to extend your library with a dictionary ordered on the municipality name, something like:
```
{'ABANO TERME': {'code': 'A001', 'name': 'ABANO TERME', 'province': 'PD'},
 'ABBADIA CERRETO': {'code': 'A004', 'name': 'ABBADIA CERRETO', 'province': 'LO'},
 ...
}
```
I'd like to retrieve the Belfiore code and the province given a municipality name, but since there's only a list of municipalities in data.__MUNICIPALITIES, each search costs `O(n)`.

Moreover, since `codicefiscale.__DATA`, `data.__MUNICIPALITIES` and `data.__COUNTRIES` are defined with the double underscore, in order to use them in my project, I had to use getattr on the modules due to name mangling.
Wouldn't a single underscore "suffice"?

So I'd like to propose two PRs: the first creating a new __MUNICIPALITIES dictionary with municipality names as keys (I know that inside __DATA there is already, but the names are slugified) and the second adding some "aliases" with a single leading underscore pointing to __DATA, __MUNICIPALITIES and __COUNTRIES (in order not to break existing setups).

Thanks!

**Comment by fabiocaccamo** [comment]
@bebosudo I understand, I will replace the double underscores with single ones.

I think that a new `__MUNICIPALITIES` dict would not be useful, so if you need it you should create it one the fly (be careful because the `name` attribute sometimes contains multiple names joined by a `/`).

Any suggestion about new features would be appreciated.

PS. I'm glad that you like this lib, consider to star it :)

**Comment by bebosudo** [comment]
Starred ;)
