### ISSUE TITLE
Unactive municipalities cannot be retrieved

### ISSUE THREAD

**Issue by danisana** [fabiocaccamo/python-codicefiscale#23]
**Python version**
3.9.9

**Package version**
0.4.0

**Current behavior (bug description)**
Decoding does not work for inactive municipalities, since only active ones are considered in
```
for municipality in municipalities:
   if not municipality["active"]:
      continue
```

**Expected behavior**
inactive municipalities data should be considered.
When multiple entries are available, take the one  where  **birthday** falls within **date_created** and **date_deleted**

**Comment by fabiocaccamo** [comment]
@danisana I'm aware of this problem, this issue is strictly related to #12.

When encoding/decoding a CF the right municipality should be the municipality that was active when the subject is born.

I recently updated the data source to be able to solve this issue, but actually I have not time work on it.

If you have time to work on it and submit a well tested PR, it would be great!

**Comment by fabiocaccamo** [comment]
@danisana thank you for contributing, you can upgrade to in `0.5.0` version.
